# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(313, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hashtags = QtWidgets.QListWidget(self.centralwidget)
        self.hashtags.setGeometry(QtCore.QRect(20, 80, 271, 111))
        self.hashtags.setObjectName("hashtags")
        self.btn_del = QtWidgets.QPushButton(self.centralwidget)
        self.btn_del.setGeometry(QtCore.QRect(250, 40, 41, 31))
        self.btn_del.setObjectName("btn_del")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(210, 40, 41, 31))
        self.btn_add.setObjectName("btn_add")
        self.hashtag = QtWidgets.QLineEdit(self.centralwidget)
        self.hashtag.setGeometry(QtCore.QRect(20, 50, 181, 20))
        self.hashtag.setObjectName("hashtag")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 91, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 240, 171, 41))
        self.label_8.setObjectName("label_8")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(20, 530, 271, 51))
        self.btn_start.setObjectName("btn_start")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 280, 271, 181))
        self.textEdit.setObjectName("textEdit")
        self.btn_get_hashtags = QtWidgets.QPushButton(self.centralwidget)
        self.btn_get_hashtags.setGeometry(QtCore.QRect(20, 200, 141, 31))
        self.btn_get_hashtags.setObjectName("btn_get_hashtags")
        self.btn_clear_hashtags = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear_hashtags.setGeometry(QtCore.QRect(170, 200, 121, 31))
        self.btn_clear_hashtags.setObjectName("btn_clear_hashtags")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 480, 281, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 313, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_del.setText(_translate("MainWindow", "제거"))
        self.btn_add.setText(_translate("MainWindow", "추가"))
        self.label_7.setText(_translate("MainWindow", "키워드"))
        self.label_8.setText(_translate("MainWindow", "로그"))
        self.btn_start.setText(_translate("MainWindow", "시작"))
        self.btn_get_hashtags.setText(_translate("MainWindow", "불러오기"))
        self.btn_clear_hashtags.setText(_translate("MainWindow", "전체 삭제"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
